CREATE TABLE IF NOT EXISTS Account (
    id UUID PRIMARY KEY,
    username VARCHAR(25) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS Conversation (
    id UUID PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    last_sent timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS Message (
    -- https://stackoverflow.com/questions/72402946/h2-auto-increment-not-working-after-update-from-1-4-200-to-2-1-212
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID NOT NULL,
    conversation_id UUID NOT NULL,
    sent_at timestamp NOT NULL,
    contents varchar(1000) NOT NULL,
    attachment_url varchar(100),
    edited BOOLEAN,

    FOREIGN KEY (account_id) REFERENCES Account(id) ON DELETE CASCADE,
    FOREIGN KEY (conversation_id) REFERENCES Conversation(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Participant (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    account_id UUID NOT NULL,
    conversation_id UUID NOT NULL,
    last_read timestamp NOT NULL,
    role VARCHAR(16),

    FOREIGN KEY (account_id) REFERENCES Account(id) ON DELETE CASCADE,
    FOREIGN KEY (conversation_id) REFERENCES Conversation(id) ON DELETE CASCADE,
    UNIQUE (account_id, conversation_id)
);