package com.webapp.example.conversation;

import com.webapp.example.account.Account;
import com.webapp.example.participant.Participant;
import com.webapp.example.participant.ParticipantRepository;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Service;

@Service
public class ConversationService {
  private final ConversationRepository conversationRepository;
  private final ParticipantRepository participantRepository;

  ConversationService(
      ConversationRepository conversationRepository, ParticipantRepository participantRepository) {
    this.conversationRepository = conversationRepository;
    this.participantRepository = participantRepository;
  }

  /**
   * Returns true if the account is in the conversation
   *
   * @param accountid
   * @param conversationId
   * @return boolean
   */
  public boolean isAccountInConversation(UUID accountid, UUID conversationId) {
    return participantRepository.isAccountInConversation(accountid, conversationId);
  }

  /**
   * Returns a list of conversations where account is a participant
   *
   * @param account
   * @return List of conversations
   */
  public List<Conversation> getMyConversations(Account account) {
    List<Participant> participants = participantRepository.findAllWithAccount(account);
    List<Conversation> conversations = new ArrayList<Conversation>();
    for (Participant p : participants) {
      conversations.add(conversationRepository.findById(p.conversationId()).get());
    }
    sortByTime(conversations);
    return conversations;
  }

  /**
   * Creates conversation, returns early if conversation with all accounts already exists.
   *
   * @param accounts
   */
  public void createConversation(List<Account> accounts) {
    UUID conversationId = UUID.randomUUID();
    String title = "";
    for (int i = 0; i < accounts.size(); i++) {
      title += accounts.get(i).username();
      if (i < accounts.size() - 1) {
        title += " & ";
      }
    }

    List<UUID> accountIds = new ArrayList<UUID>();
    for (Account account : accounts) {
      accountIds.add(account.id());
    }

    if (participantRepository.commonConversationExists(accountIds)) {
      return;
    }

    conversationRepository.create(new Conversation(conversationId, title, LocalDateTime.now()));
    for (int i = 0; i < accounts.size(); i++) {
      participantRepository.create(
          new Participant(
              null,
              accounts.get(i).id(),
              conversationId,
              "ROLE_USER")); // Id will be auto-generated by the database
    }
  }

  /**
   * Merge sort by recency
   *
   * @param list
   */
  private void sortByTime(List<Conversation> list) {
    if (list.size() >= 2) {

      int mid = list.size() / 2;

      List<Conversation> left = new ArrayList<>(list.subList(0, mid));
      List<Conversation> right = new ArrayList<>(list.subList(mid, list.size()));

      sortByTime(left); // recursive sortByTime where 'list' now becomes 'left'
      sortByTime(right);
      merge(list, left, right);
    }
  }

  private static void merge(
      List<Conversation> list, List<Conversation> left, List<Conversation> right) {
    int i = 0, j = 0, k = 0;

    while (i < left.size() && j < right.size()) {
      if (left.get(i).lastSent().isAfter(right.get(j).lastSent())) {
        list.set(k++, left.get(i++));
      } else {
        list.set(k++, right.get(j++));
      }
    }
    while (i < left.size()) {
      list.set(k++, left.get(i++));
    }
    while (j < right.size()) {
      list.set(k++, right.get(j++));
    }
  }
}
